### ISSUE TITLE
Palette slots availability issue

### ISSUE THREAD

**Issue by Kalarie1** [kimwnasptd/OWM-Qt#10]
After you reach palette ID 0x11FF newly imported overworld sprites won't get their proper palette, but the palette of palette slot 0x11FF. Even though there are still palette slots available. Palette slots that have been used before (but are empty now) are not re-used by the tool at the moment.

**Comment by kimwnasptd** [comment]
IIRC Palette slot 0x11FF designates the end of the Palette Table. For this reason OWM [avoids using this id](https://github.com/kimwnasptd/OWM-Qt/blob/master/core_files/ImageEditor.py#L458) when inserting a new Palette.

It seems weird that there is even an OW that is using this palette id. Do all of these OWs have palette id 0x11FF on their [OW Data](https://github.com/kimwnasptd/OWM-Qt/wiki/Inner-Workings#ow-data)?

I'm guessing that you are using the [rom you mentioned](https://github.com/kimwnasptd/OWM-Qt/issues/9#issuecomment-529695736) in another issue, which I think has JPAN engine installed. So I tried to open it with OWM's `Open and Analyze...`  but there were some issues with the palette table. The old table at `0x3A51C8` still exists, which leads OWM to think that this one is the palette table and not the one at `0x16A2D8`. 

When OWM repoints the palette table it should move the data and not leave any replica behind. Do you have any more insight as to why the old data is still there?

On another note, I'm using this Profile and managed to open the ROM
```
[JPAN]
OW Table Pointers = 0x1A2000
Palette Table Pointers Address = 0x5F570, 0x5F570, 0x5F570
```
( On a first glance I don't like the fact that it needs _exactly_ three pointers for the palette table but this can be fixed in a separate issue )

The ROM has 228 OWs and the biggest palette id I can see being used is `0x11F8`. Is this the expected state of the ROM? I'll try importing some more OWs and see how it behaves with regard to id `0x11FF`.

**Comment by Kalarie1** [comment]
![Overworld Manager Problem](https://user-images.githubusercontent.com/55097055/64994276-72ad3400-d8d8-11e9-9deb-79c2f9689c22.png)
The first time I implement an overworld sprite when attempting to use palette slot 0x11FF, most sprites are looking glitched in OWM.
After saving and restarting Overworld Manager and importing a new sprite sheet, Overworld Manager imports a new palette slot at 0x11FF. After that, all imported sheets will get palette slot 0x11FF by default and will have an incorrect palette (like that Charizard).

**Comment by Kalarie1** [comment]
Yes, all of these OW's have palette id 0x11FF in their OW Data.

I have no idea how the old data could still be there, I never implemented a seperate table manually. Afaik, OWM is the only program that handled the palette table in my ROM.

This is the profile my settings file is showing:
`[JPAN]
OW Table Pointers = 0x1A2000
Palette Table Pointers Address = 0x5F4D8, 0x5F570, 0x5F5C8`

I don't expect to import a lot more overworld sprites, I just like to replace the pokemon sprites that are currently in the ROM with the ones I sent you through e-mail;)

**Comment by kimwnasptd** [comment]
Thanks for the details @Kalarie1, the fix should be one master now. OWM should now be able to correctly handle the palette ID for 0x1200 and up.

@Kalarie1 you can close the issue whenever you feel confident that this bug is resolved. We can also re-open the issue if it arises again.

**Comment by Kalarie1** [comment]
Nice! I'll check it out tomorrow;)
