### ISSUE TITLE
Free Space Finding

### ISSUE THREAD

**Issue by Kalarie1** [kimwnasptd/OWM-Qt#8]
In my view it would be a good idea to let the tool search for free space past offset 0x800000 (for example), or make it customizable to decide from which offset to search for free space. I think the tool searches for free space from offset 0x000000 by default which may lead to data corruption in some cases.

**Comment by kimwnasptd** [comment]
Hi there @Kalarie1 long time no see!

Thanks for reporting in. Would you mind opening separate issues for each of your points so that we can track and discuss each one seperately?

**Comment by Kalarie1** [comment]
If everything went well, there should be three seperate issues at the moment;)

**Comment by kimwnasptd** [comment]
Nice, thanks @Kalarie1!

> I think the tool searches for free space from offset 0x000000 by default which may lead to data corruption in some cases.

Yes that's its behavior. Have you experienced a case where the data of the ROM was corrupted because the searching for free space started from 0x000000? What data was replaced that shouldn't have been?

**Comment by Kalarie1** [comment]
Yup, I remember experiencing problems with the flight map after saving new overworld sprites in OWM (The game crashed after opening the flight map).

It happened because OWM wrongly assumed the FF bytes at 0xC3670 were free space, but those are ''placeholder'' bytes for the custom flight map routine that I used for my town map (A routine that can be applied in advancemap for custom town maps).

Momentarily replacing them with other bytes before using OWM prevented corruption. But of course it would be more convenient if OWM could not overwrite that data in the first place.

If you need the ROM I'm currently using, you could download the latest patch of Orange Islands in this thread on PC: https://www.pokecommunity.com/showthread.php?t=402242

Hope this helps;)

**Comment by kimwnasptd** [comment]
I see, then I think the most flexible way to tackle this would be to add a `Reserved Addresses` field in the ini on each ROM's Profile. This field would be a list of ranges, something like:
```
OW Table Pointers = 0x...
Palette Table Pointers Addreess = 0x..., 0x..., 0x...
Reserved Addresses = 0x000000-0x800000, 0x0A0000-0x0A1000
```

This field would determine which addresses OWM should _not_ be using. When the user would use the `Open and Analyze...` functionality the UI could ask the user to enter these ranges for the new ROM so that OWM can take them into consideration when repointing the initial tables.

The main changes for this would need to happen in the way the `find_free_space` is being used. Although the way that common data is shared between the different modules is very clumsy, global vars per module, I think it should be doable.

**Comment by Kalarie1** [comment]
Sounds good!

**Comment by kimwnasptd** [comment]
First half for closing this issue is on master branch. WIth [this commit](https://github.com/kimwnasptd/OWM-Qt/commit/f00cf902e475ec6802fd01ff0dce0f346acb5e85), we can add a `Reserved Regions = {start1}-{end1}, ...` line after the `Palette Table Pointers Address` to specify which ROM regions OWM shouldn't use.

The next part would be to allow the user to specify this value when they use `Open and Analyze...` from the GUI. 

For now the `Reserved Regions` field can be used with `Open and Analyze...` by
1. Click `Open and Analyze...` and select the ROM. This will create the ini Profile for that ROM
2. When it's finished, DON"T save the ROM
3. Edit the `Reserved Regions = ` of the new Profile that was created with your desired values
4. Open the ROM by using the `Open ROM...` action
5. OWM will find the existing Profile and try to open the ROM with that one

**Comment by Kalarie1** [comment]
I tested this issue and after putting in reserved region = 0x000000 - 0x800000, the flight map worked fine after importing a new sprite. So it seems to work perfectly, thanks for your hard work on this tool! I'll set this issue and the palette id issue as solved!

**Comment by kimwnasptd** [comment]
Glad to hear! Although I should note that I haven't really though this change thoroughly. 

One corner case that comes to mind would be if the provided ranges are already used from OWM. I think it should be ok in all of the functions it uses, but would be a good debugging step to check if in the future we observe weird behaviors.

@Kalarie1 If you notice something weird that might be related feel free to reopen this issue
