### ISSUE TITLE
Uncommon Dimension Issue

### ISSUE THREAD

**Issue by Kalarie1** [kimwnasptd/OWM-Qt#9]
Something I ran into recently is that when importing new frame sheets for NPC's that have a different dimension than 16x32 or 32x32, the overworld sprites often look glitchy in-game after importing (they look correct in OWM). The graphics are imported correctly, but the overworld sprite data does not correspond with the size of the overworld sprite. That's why I had to edit the overworld sprite data manually in a hex editor. Which takes a little time, but is not too bad for me. However, a lot of people have no idea what to do if something like this happens.

When importing a 64x64 sprite the sizes in the data are not updated to 00 40 00 40 (and a 08 preceding them) and the first two pointers should also be changed to 20 37 3A 08 D0 38 3A 08 to make it work correctly.

This can all be done manually of course, but wouldn't it be nice if the tool would do it for you?

**Comment by kimwnasptd** [comment]
First off, could you provide the ROM you are using so I can try and reproduce what you see?

IIUC 64x64 is the type 4. If you go to `OWM/Files/<rom-profile>` then there will be files named `Template{1-8}` in it. When resizing a sprite OWM will use these templates to fill the OW Data. In my templates for Fire Red 1.1 the size is set to `40 00 40 00`, is it different for your Template4?

The two pointers you mentioned which one of [these](https://github.com/kimwnasptd/OWM-Qt/wiki/Inner-Workings#ow-data) are they? Is the Profile you are using for your ROM the correct one that corresponds to your ROM?

**Comment by Kalarie1** [comment]
The ROM I'm using can be downloaded from this thread: https://www.pokecommunity.com/showthread.php?t=402242
If you need a savefile let me know;)

These are the hex data in my template 4 (for BPRE): FF FF 14 11 FF 11 00 08 40 00 40 00 1A 00 00 00 20 37 3A 08 D0 38 3A 08 68 33 3A 08 A8 1C 3A 08 FC 1C 23 08

Which look correct to me actually, so I don't expect that to be the problem.

These are the hex data in my template 4 (for JPAN): FF FF 42 11 02 11 00 02 20 00 20 00 10 00 02 00 18 37 3A 08 F0 37 3A 08 68 33 3A 08 AC A2 80 08 FC 1C 23 08

So that's (^) probably the problem:)

The pointers I mentioned are the ''Pointer 1'' and the ''Size-Draw Pointer''

**Comment by kimwnasptd** [comment]
From your PC rom link (very nice work btw!) I can see that it is utilizing the JPAN engine. Which version of Fire Red is it using? Is it v1.0 or v1.1?

Also, when editing your ROM with OWM do you use the JPAN or the BPRE Profile?

**Comment by Kalarie1** [comment]
It's using Fire Red 1.0 (Squirrels) as a base and I'm using the JPAN Profile.

**Comment by Kalarie1** [comment]
The tool doesn't seem to make a good profile for JPAN by default, the templates generated for it are not correct in case of template 3,4 and 5 (Not sure about template 6-8, don't know what they are used for). Replacing them manually with the ones generated for the BPRE profile fixes it. But it would be nicer if the tool generated correct ones in the first place.

**Comment by kimwnasptd** [comment]
6-8 are only used from S/R/Em ROMs IIRC.

The templates are created by using the OW Data of OWs with different dimensions, in the order it finds these OWs when opening with `Open and Analyze...`. Will need to deterine if the problem lies on how OWM copies the OW Data, when creating the Templates, or if the wrong pointers are set from the JPAN ips.

I'll use the FIre Red 1.0 Squirrels with JPAN since this is the ROM we discussed and I'll report back

**Comment by kimwnasptd** [comment]
Yup, turns out OWM was not checking the correct OWs to copy the OW Data from for JPAN roms.

The problem in the first place was the fact that when creating the Templates it would look at specific OWs (like OW 0 for 16x32) and just copy their OW Data as Templates to use. The problem with that approach is that ROMs that had already been edited might have changed the size of the specific OWs that OWM use to create the templates and thus the templates will be wrong.

This is an important issue, since one of the main points I wanted OWM to have was to be able to work with any arbitrary ROM. I'll work on a fix asap.

**Comment by kimwnasptd** [comment]
The fix is merged with master. The template logic should be completely modular and work for any ROM like custom ones or multilinguals.

Also made OWM to include a comment for every Profile it creates in the ini to log the ROM file that the Profile was created for. This should make it easier to keep track of which Profiles are for which ROMs.

Thanks for reporting this error @Kalarie1 !

**Comment by Kalarie1** [comment]
Nice! I'll check it out;)

**Comment by Kalarie1** [comment]
From what I've tested it works perfectly now! I'll set this issue as closed for now!
